/* Generated by cbindgen — do not edit */

#ifndef CSTX_FFI_H
#define CSTX_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct CstxGraph CstxGraph;

struct CstxGraph *cstx_graph_new(void);

void cstx_graph_free(struct CstxGraph *g);

void cstx_graph_load_easm(struct CstxGraph *g);

int cstx_graph_register_schema(struct CstxGraph *g,
                               const char *node_type,
                               const char *json_schema_str,
                               const char *value_field);

int cstx_graph_add_join_rule(struct CstxGraph *g,
                             const char *left_type,
                             const char *right_type,
                             const char *relation,
                             const char *left_key,
                             const char *right_key,
                             int predicted,
                             const char *left_target_id,
                             const char *right_source_id);

int cstx_graph_add_node(struct CstxGraph *g,
                        const char *node_type,
                        const char *cstx_id,
                        const char *payload_json,
                        const char *sources_json,
                        uint64_t cstx_flags);

int cstx_graph_add_edge(struct CstxGraph *g,
                        const char *source_id,
                        const char *target_id,
                        const char *relation,
                        const char *data_source);

int cstx_graph_add_nodes_batch(struct CstxGraph *g,
                               const char *nodes_json,
                               char **out,
                               uintptr_t *out_len);

int cstx_graph_add_edges_batch(struct CstxGraph *g, const char *edges_json);

int cstx_graph_link(struct CstxGraph *g,
                    const char *source,
                    const uint8_t *data,
                    uintptr_t data_len,
                    char **out,
                    uintptr_t *out_len);

int cstx_graph_ingest_native(struct CstxGraph *g,
                             const char *plugin_name,
                             const char *artifact,
                             const uint8_t *data,
                             uintptr_t data_len,
                             char **out,
                             uintptr_t *out_len);

int cstx_graph_has_native_artifact(struct CstxGraph *g, const char *artifact);

int cstx_graph_ingest_jsonl(struct CstxGraph *g,
                            const char *node_type,
                            const uint8_t *data,
                            uintptr_t data_len,
                            const char *id_expr,
                            const char *data_source,
                            char **out,
                            uintptr_t *out_len);

int cstx_graph_link_nodes(struct CstxGraph *g,
                          const char *data_source,
                          char **out,
                          uintptr_t *out_len);

char *cstx_graph_node(struct CstxGraph *g, const char *node_id);

char *cstx_graph_nodes(struct CstxGraph *g, const char *type_filter);

char *cstx_graph_edges(struct CstxGraph *g, const char *relation);

char *cstx_graph_node_types(struct CstxGraph *g);

char *cstx_graph_neighbors(struct CstxGraph *g, const char *node_id);

char *cstx_graph_to_json(struct CstxGraph *g);

char *cstx_graph_node_payload(struct CstxGraph *g, const char *node_id);

int cstx_graph_contains_node(struct CstxGraph *g, const char *node_id);

uintptr_t cstx_graph_node_count(struct CstxGraph *g);

uintptr_t cstx_graph_edge_count(struct CstxGraph *g);

char *cstx_graph_node_ids(struct CstxGraph *g);

char *cstx_graph_stats(struct CstxGraph *g);

char *cstx_graph_all_nodes_json(struct CstxGraph *g);

int cstx_transform(const char *source_type,
                   const uint8_t *data,
                   uintptr_t data_len,
                   char **out,
                   uintptr_t *out_len);

void cstx_free_string(char *s);

const char *cstx_version(void);

char *cstx_supported_artifacts(void);

#endif  /* CSTX_FFI_H */
