// @generated by cstx-codegen — DO NOT EDIT.

package cstx

import "encoding/json"

type Domain struct {
	nodeHeader
	Host                 string       `json:"host"`
}

type Subdomain struct {
	nodeHeader
	Host                 string       `json:"host"`
	IsTld                bool         `json:"is_tld,omitempty"`
	Ttl                  int64        `json:"ttl,omitempty"`
	Resolver             []string     `json:"resolver,omitempty"`
	A                    []string     `json:"a,omitempty"`
	Aaaa                 []string     `json:"aaaa,omitempty"`
	Cname                []string     `json:"cname,omitempty"`
	Mx                   []string     `json:"mx,omitempty"`
	Ns                   []string     `json:"ns,omitempty"`
	Txt                  []string     `json:"txt,omitempty"`
}

type Ip struct {
	nodeHeader
	Ip                   string       `json:"ip"`
	Country              string       `json:"country,omitempty"`
	Area                 string       `json:"area,omitempty"`
	AsnNumber            string       `json:"asn_number,omitempty"`
	AsName               string       `json:"as_name,omitempty"`
	CdnName              string       `json:"cdn_name,omitempty"`
	CloudName            string       `json:"cloud_name,omitempty"`
	WafName              string       `json:"waf_name,omitempty"`
	Cdn                  bool         `json:"cdn,omitempty"`
	Cloud                bool         `json:"cloud,omitempty"`
	Waf                  bool         `json:"waf,omitempty"`
}

type Cidr struct {
	nodeHeader
	Cidr                 string       `json:"cidr"`
}

type Port struct {
	nodeHeader
	Ip                   string       `json:"ip"`
	Port                 string       `json:"port"`
	Protocol             string       `json:"protocol"`
}

type App struct {
	nodeHeader
	AppId                string       `json:"app_id"`
	Url                  string       `json:"url,omitempty"`
	Frameworks           []string     `json:"frameworks,omitempty"`
	Title                string       `json:"title,omitempty"`
	Midware              string       `json:"midware,omitempty"`
	Status               string       `json:"status,omitempty"`
	StatusCode           int64        `json:"status_code,omitempty"`
	Host                 string       `json:"host,omitempty"`
	ContentType          string       `json:"content_type,omitempty"`
	BodyLength           int64        `json:"body_length,omitempty"`
	HeaderLength         int64        `json:"header_length,omitempty"`
}

type Url struct {
	nodeHeader
	Scheme               string       `json:"scheme"`
	Host                 string       `json:"host,omitempty"`
	Port                 string       `json:"port,omitempty"`
	Path                 string       `json:"path,omitempty"`
	Ip                   string       `json:"ip,omitempty"`
	StatusCode           int64        `json:"status_code,omitempty"`
	Title                string       `json:"title,omitempty"`
	BodyLength           int64        `json:"body_length,omitempty"`
	ContentType          string       `json:"content_type,omitempty"`
	RedirectUrl          string       `json:"redirect_url,omitempty"`
	Frameworks           []string     `json:"frameworks,omitempty"`
}

type Framework struct {
	nodeHeader
	Name                 string       `json:"name"`
	Part                 string       `json:"part,omitempty"`
	Vendor               string       `json:"vendor,omitempty"`
	Product              string       `json:"product,omitempty"`
	Version              string       `json:"version,omitempty"`
	Tags                 []string     `json:"tags,omitempty"`
	IsFocus              bool         `json:"is_focus,omitempty"`
	Sources              []string     `json:"sources,omitempty"`
}

type Vuln struct {
	nodeHeader
	Value                string       `json:"value"`
	VulnId               string       `json:"vuln_id,omitempty"`
	Name                 string       `json:"name,omitempty"`
	AssetId              string       `json:"asset_id,omitempty"`
	Severity             string       `json:"severity,omitempty"`
	Tags                 []string     `json:"tags,omitempty"`
	Ip                   string       `json:"ip,omitempty"`
	Host                 string       `json:"host,omitempty"`
	Port                 string       `json:"port,omitempty"`
	Protocol             string       `json:"protocol,omitempty"`
	Scheme               string       `json:"scheme,omitempty"`
	Url                  string       `json:"url,omitempty"`
	Path                 string       `json:"path,omitempty"`
	Pocname              string       `json:"pocname,omitempty"`
	Request              string       `json:"request,omitempty"`
	Response             string       `json:"response,omitempty"`
	Username             string       `json:"username,omitempty"`
	Password             string       `json:"password,omitempty"`
}

type Certificate struct {
	nodeHeader
	Fingerprint          string       `json:"fingerprint"`
	Serial               string       `json:"serial,omitempty"`
	Issuer               string       `json:"issuer,omitempty"`
	Subject              string       `json:"subject,omitempty"`
	NotBefore            string       `json:"not_before,omitempty"`
	NotAfter             string       `json:"not_after,omitempty"`
	San                  []string     `json:"san,omitempty"`
	Host                 string       `json:"host,omitempty"`
	Ip                   string       `json:"ip,omitempty"`
}

type Company struct {
	nodeHeader
	Name                 string       `json:"name"`
	Perc                 string       `json:"perc,omitempty"`
	Tycid                string       `json:"tycid,omitempty"`
	Icp                  string       `json:"icp,omitempty"`
	Parent               string       `json:"parent,omitempty"`
}

type Icp struct {
	nodeHeader
	Icp                  string       `json:"icp"`
	Sub                  string       `json:"sub,omitempty"`
	Date                 string       `json:"date,omitempty"`
	Company              string       `json:"company,omitempty"`
	Title                string       `json:"title,omitempty"`
	Domain               string       `json:"domain,omitempty"`
	Ip                   string       `json:"ip,omitempty"`
}

type Bucket struct {
	nodeHeader
	Provider             string       `json:"provider,omitempty"`
	Name                 string       `json:"name,omitempty"`
	Region               string       `json:"region,omitempty"`
	Endpoint             string       `json:"endpoint"`
	Acl                  string       `json:"acl,omitempty"`
	ObjectCount          int64        `json:"object_count,omitempty"`
	KnownPaths           []string     `json:"known_paths,omitempty"`
	SourceUrl            string       `json:"source_url,omitempty"`
}

type Endpoint struct {
	nodeHeader
	Url                  string       `json:"url"`
	Method               string       `json:"method,omitempty"`
	Path                 string       `json:"path,omitempty"`
	ContentType          string       `json:"content_type,omitempty"`
	StatusCode           int64        `json:"status_code,omitempty"`
	Source               string       `json:"source,omitempty"`
	SourceUrl            string       `json:"source_url,omitempty"`
	Parameters           []string     `json:"parameters,omitempty"`
	Tags                 []string     `json:"tags,omitempty"`
}

type Host struct {
	nodeHeader
	Hostname             string       `json:"hostname"`
	LocalIps             []string     `json:"local_ips,omitempty"`
	GatewayIps           []string     `json:"gateway_ips,omitempty"`
	DnsServers           []string     `json:"dns_servers,omitempty"`
	DomainName           string       `json:"domain_name,omitempty"`
	DomainRole           string       `json:"domain_role,omitempty"`
}

type Repository struct {
	nodeHeader
	Provider             string       `json:"provider,omitempty"`
	Name                 string       `json:"name,omitempty"`
	Url                  string       `json:"url"`
	Owner                string       `json:"owner,omitempty"`
	Description          string       `json:"description,omitempty"`
	Stars                int64        `json:"stars,omitempty"`
	IsFork               bool         `json:"is_fork,omitempty"`
	MatchedDorks         []string     `json:"matched_dorks,omitempty"`
}

type Secret struct {
	nodeHeader
	Kind                 string       `json:"kind,omitempty"`
	Detector             string       `json:"detector,omitempty"`
	Redacted             string       `json:"redacted,omitempty"`
	Fingerprint          string       `json:"fingerprint"`
	Source               string       `json:"source,omitempty"`
	SourceUrl            string       `json:"source_url,omitempty"`
	FilePath             string       `json:"file_path,omitempty"`
	Line                 int64        `json:"line,omitempty"`
	Commit               string       `json:"commit,omitempty"`
	Verified             bool         `json:"verified,omitempty"`
	Severity             string       `json:"severity,omitempty"`
}

// SCONode is the common interface for all CSTX graph nodes.
type SCONode interface {
	CstxType() string
	CstxID() string
}

type nodeHeader struct {
	Type string `json:"cstx_type"`
	ID   string `json:"cstx_id"`
}

func (h nodeHeader) CstxType() string { return h.Type }
func (h nodeHeader) CstxID() string   { return h.ID }

// ParseSCONode unmarshals a JSON node into the correct typed struct.
func ParseSCONode(data []byte) (SCONode, error) {
	var h nodeHeader
	if err := json.Unmarshal(data, &h); err != nil {
		return nil, err
	}
	switch h.Type {
	case "domain":
		var v Domain; err := json.Unmarshal(data, &v); return &v, err
	case "subdomain":
		var v Subdomain; err := json.Unmarshal(data, &v); return &v, err
	case "ip":
		var v Ip; err := json.Unmarshal(data, &v); return &v, err
	case "cidr":
		var v Cidr; err := json.Unmarshal(data, &v); return &v, err
	case "port":
		var v Port; err := json.Unmarshal(data, &v); return &v, err
	case "app":
		var v App; err := json.Unmarshal(data, &v); return &v, err
	case "url":
		var v Url; err := json.Unmarshal(data, &v); return &v, err
	case "framework":
		var v Framework; err := json.Unmarshal(data, &v); return &v, err
	case "vuln":
		var v Vuln; err := json.Unmarshal(data, &v); return &v, err
	case "certificate":
		var v Certificate; err := json.Unmarshal(data, &v); return &v, err
	case "company":
		var v Company; err := json.Unmarshal(data, &v); return &v, err
	case "icp":
		var v Icp; err := json.Unmarshal(data, &v); return &v, err
	case "bucket":
		var v Bucket; err := json.Unmarshal(data, &v); return &v, err
	case "endpoint":
		var v Endpoint; err := json.Unmarshal(data, &v); return &v, err
	case "host":
		var v Host; err := json.Unmarshal(data, &v); return &v, err
	case "repository":
		var v Repository; err := json.Unmarshal(data, &v); return &v, err
	case "secret":
		var v Secret; err := json.Unmarshal(data, &v); return &v, err
	default:
		return nil, nil
	}
}
