// @generated by cstx-codegen — DO NOT EDIT.

package cstx

const (
	RelResolve      = "resolve"
	RelOpen         = "open"
	RelHasSubdomain = "has-subdomain"
	RelContain      = "contain"
	RelHosts        = "hosts"
	RelUses         = "uses"
	RelRefers       = "refers"
	RelSecuredBy    = "secured_by"
	RelExploit      = "exploit"
	RelAffect       = "affect"
	RelInvest       = "invest"
	RelOwn          = "own"
	RelFiledFor     = "filed-for"
)

var RelationTypes = []string{
	RelResolve,
	RelOpen,
	RelHasSubdomain,
	RelContain,
	RelHosts,
	RelUses,
	RelRefers,
	RelSecuredBy,
	RelExploit,
	RelAffect,
	RelInvest,
	RelOwn,
	RelFiledFor,
}
