// @generated by cstx-codegen — DO NOT EDIT.

package cstx

const (
	RelResolve = "resolve"
	RelOpen = "open"
	RelSecuredBy = "secured_by"
	RelInvest = "invest"
	RelOwn = "own"
	RelFiledFor = "filed-for"
)

var RelationTypes = []string{
	RelResolve,
	RelOpen,
	RelSecuredBy,
	RelInvest,
	RelOwn,
	RelFiledFor,
}
